"""make CashAction model

Revision ID: 6f3678a416de
Revises: 194a88a60fdf
Create Date: 2024-09-23 16:13:28.114480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f3678a416de'
down_revision: Union[str, None] = '194a88a60fdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_actions',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('action', sa.Enum('DEPOSIT', 'WITHDRAWAL', name='cashactiontype', native_enum=False), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=10), nullable=False),
    sa.Column('execution_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('portfolio_id', mysql.CHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cash_actions_id'), 'cash_actions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cash_actions_id'), table_name='cash_actions')
    op.drop_table('cash_actions')
    # ### end Alembic commands ###
